# 使用PyTorch进行数据操作

导入torch库

In [1]:
import torch

用`arange()`创建一个从0到11的数组

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

可以通过`shape`访问矩阵的维度

In [3]:
x.shape

torch.Size([12])

可以通过`numel()`访问矩阵的元素数量。

In [5]:
x.numel()

12

可以用`reshape()`改变形状。例如`reshape(3,4)`就是将其改变为3行4列。

In [6]:
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

可以通过`zeros()`或者`ones()`函数来创建一个全零或者全一的矩阵。

In [8]:
torch.zeros(2,3,4) # 创建深度为2,3列4行的零矩阵

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

可以通过`tensor()`创建特定的张量

In [10]:
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])